### ISSUE TITLE
Discuss 

### ISSUE THREAD

**Issue by adrian-barbu** [AdrianChandler0/hopeTeam0133#1]
Hi, Hope you're doing well.
I'm now looking for a RN engineer, I would like to get connection soon.

**Comment by adrian-barbu** [comment]
hello, what's your email?

**Comment by adrian-barbu** [comment]
What's your skype? I would like to discuss some project

**Comment by hopeTeam01** [comment]
okay

**Comment by adrian-barbu** [comment]
I'm your brother

**Comment by adrian-barbu** [comment]
Telegram is also okay

**Comment by hopeTeam01** [comment]
okay. sorry just 1min. and then.
would u please clear history?

**Comment by hopeTeam01** [comment]
s -> 4b31bfe831e41f74

**Comment by adrian-barbu** [comment]
thanks
